name: Java CI
on: push
jobs:
  Clone-down: 
    name: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    name: Test
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: test
        uses: actions/upload-artifact@v2
        run: ci/unit-test-app.sh   

  Build:
    name: Build
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: build app
        uses: actions/upload-artifact@v2
        run: chmod +x ci/build-app.sh && ci/build-app.sh